### ISSUE TITLE
When will the new version be released

### ISSUE THREAD

**Issue by dreampen123** [39ff/squid-db-auth-web#3]
When will the new version be released？

**Comment by 39ff** [comment]
This month.

**Comment by 39ff** [comment]
In March.

**Comment by dreampen123** [comment]
Can I add the expiration date of the account?

For example, you can set the account to expire after one year

thanks  a lot

**Comment by dreampen123** [comment]
today is 2022.3.1
Oh, I look forward to i

**Comment by 39ff** [comment]
yes
Date and time TBD.

**Comment by dreampen123** [comment]
ok waiting!!!
