### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by dreampen123** [39ff/squid-db-auth-web#9]
**Warning: require(/www/wwwroot/k.wqidian.com/public/../vendor/autoload.php): Failed to open stream: No such file or directory in /www/wwwroot/k.wqidian.com/public/index.php on line 34

Fatal error: Uncaught Error: Failed opening required '/www/wwwroot/k.wqidian.com/public/../vendor/autoload.php' (include_path='.:') in /www/wwwroot/k.wqidian.com/public/index.php:34 Stack trace: #0 {main} thrown in /www/wwwroot/k.wqidian.com/public/index.php on line 34**

could you help me?
thx

**Comment by 39ff** [comment]
done 
https://github.com/39ff/squid-db-auth-web/releases/tag/v2.0.0
